name: pre-commit

on: [ push, pull_request ]

jobs:

  pre-commit:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    # setup
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    # install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --quiet --upgrade pip
        python -m pip install --quiet pre-commit
    # run pre-commit
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
