name: tests-torch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.11", "3.13"]
        torch-version: ["1.10", "2.6"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch==${{ matrix.torch-version }}
        python -m pip install -e .[test]

    - name: Tests
      run: |
        pytest --ignore-glob "tests/torch/*"
