name: tests-torch

on: [ push, pull_request ]
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:

  test-minimum-requirements:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch==1.10
        pwd
        ls
        python -m pip install /home/runner/work/skrl/skrl[torch]
        python -m pip install /home/runner/work/skrl/skrl[tests]
    - name: Run tests
      run: |
        pytest --ignore-glob "tests/torch/*"
